### PR TITLE
New implementation

### PR DESCRIPTION
**Pull request by ledermann**
**PLEASE NOTE:** This is a comprehensive revision! The changes include:

- Refactoring the code by splitting it into different classes
- Moving code from `/src` to `/app`
- Simplifying the process of flipping values (this is specifically required for `bat_charge_power` only, now the ENV var is called `MQTT_FLIP_BAT_POWER` instead of `FLIP_POS_NEG_PWR_GRID` and `FLIP_POS_NEG_PWR_BATT`)
- Removing ENV var `ABS_VALUE_ONLY` because IMHO there is no use case for this
- Improving ENV configuration for InfluxDB and MQTT broker (added `MQTT_SSL`, removed `MQTT_CLIENTID`, added `INFLUX_SCHEMA`, `INFLUX_PORT`, `INFLUX_MEASUREMENT`)
- Adding topics to separate strings (`MQTT_TOPIC_MPP1_POWER`, `MQTT_TOPIC_MPP2_POWER`, `MQTT_TOPIC_MPP3_POWER`)
- Improving error handling by using `retry` if the MQTT broker or InfluxDB are not functioning properly
- Merging the `.env` examples for `ioBroker` and `evcc` into a single file
- Introducing tests via `minitest`, `vcr`, `webmock`, `climate_control` and code coverage via `simplecov`. This includes a fake MQQT server borrowed from https://github.com/njh/ruby-mqtt
- Incorporating an (opinionated) `RuboCop` configuration
- Upgrading Ruby to version 3.2.2
- Modifying the GitHub Actions setup to align with `SENEC-Collector`
- Some smaller cleanup

The new code is tested with both `ioBroker` and `evcc` against my `SENEC.Home V3`.

I am interested in continuing to maintain and develop the project in the @solectrus organization, with the consent of @loebse and @GrimmiMeloni. What are your thoughts?

### CODE REVIEW

**Comment by loebse** [comment]
Wow, these are some serious changed @ledermann 👍 

Thanks for taking the time and making the effort! I am currently looking into all the changes and trying to understand the new setup 😉 

Also, it looks like this would be way more useful when continued in your organization! I am already super happy that I was able to inspire you 😜

**Review by loebse — APPROVED** [review]

**Comment by ledermann** [comment]
Great, thanks for merging! I hope I didn't miss anything which breaks your setup.

I would be happy if you transfer the repo to the @solectrus organization (see "Settings" -> "Transfer ownership" at the bottom)

**Comment by loebse** [comment]
@ledermann looks like I am missing authorization to move the repo:
image

Can you please provide me the needed authorization?!

**Comment by ledermann** [comment]
@loebse Oops, sorry, I just added you as a member to the @solectrus organization.

**Comment by loebse** [comment]
Yes, looks good @ledermann 
Any preferences for the repo name? Keep it "mqtt-collector" ?

**Comment by ledermann** [comment]
Yes, `mqtt-collector` is fine.

**Pull request merged**
